### PR TITLE
Tighten download validation

### PR DESCRIPTION
**Pull request by deldesir**
Exit on video downloading failure

### CODE REVIEW

**Comment by holta** [comment]
Hard to test until the next time a video download actually fails?

(Or is there some way to mock up a partial test?)

**Comment by deldesir** [comment]
I am afraid it might not be possible to fully test this until this is used in a real-world scenario where a video download actually fails. I mean, with due respect, the conditional statement is straight forward.

**Comment by deldesir** [comment]
I guess however I need to find the best approach for testing those little changes and ensuring they lead to a more robust 
and reliable environment ;-)

**Comment by holta** [comment]
> Exit on video downloading failure

Why?

Exit if a single video fails to download?
(A few failed downloads are likely common when handling large numbers of videos.)

Would a better approach be to "loudly" notify the operator (and also log file) of all failed video downloads?
(While still producing a ZIM file, insofar as possible...)

**Comment by deldesir** [comment]
I thought a more strict condition makes more sense since a single download failure would mean rerunning the process for all videos.

The validation, in its current state, does allow the script to finish if some videos failed (the number of failed ones has to not exceed or equal the number of succeeded ones). It also states how many videos failed and logs all of this to a file.

**Comment by holta** [comment]
> in its current state [it] states how many videos failed [to download] and logs all of this to a file

Are we sure about this ?

**Comment by holta** [comment]
These might not be the correct assumptions below?

Either way, let's write down core assumptions, if these are not correct:

1. The more glitches the better (for now!)
2. Details of each glitch needs to be captured-in-context — so we learn from each one — via STDOUT and/or in log file `/output/run.log` ?
3. ZIM file should still be produced (if/when possible!)

**Comment by deldesir** [comment]
I am confident we can count on the existing download validation set at https://github.com/iiab/youtube/blob/f9916da238ecaccda7a290da8c17238494739441/youtube2zim/scraper.py#L308... 

Attested by these messages from a failed run:
https://paste.ubuntu.com/p/DGD2QR59z8/

`[youtube2zim: 2023-01-23 16:29:13,197] DEBUG: removing left-over files of 6 failed videos
[youtube2zim: 2023-01-23 16:29:13,198] ERROR: 6 video(s) failed to download: ['9PFhrpyWV-w', '3yH5TuLYRcs', 'Q26Z4JWVZvk', 'dhFlDkES6Ws', 'rDkaZWirNME', 'pT7vRUGeEtA']
[youtube2zim: 2023-01-23 16:29:13,198] CRITICAL: More than half of videos failed. exiting
[youtube2zim: 2023-01-23 16:29:13,198] ERROR: FAILED. An error occurred: Too much videos failed to download
[youtube2zim: 2023-01-23 16:29:13,198] ERROR: Too much videos failed to download
    raise IOError("Too much videos failed to download")
OSError: Too much videos failed to download
[youtube2zim: 2023-01-23 16:31:31,006] DEBUG: removing left-over files of 1 failed videos
[youtube2zim: 2023-01-23 16:31:31,006] ERROR: 1 video(s) failed to download: ['3yH5TuLYRcs']`

**Comment by holta** [comment]
It seems logging is current off by default, arising from:

- https://github.com/iiab/youtube/pull/5#issue-1598196152

As @deldesir uncovered, and is working hard to straighten this out, e.g. changing the default to log all warnings and all errors (with a PR coming soon likely).

**Pull request closed without merging**
