### PR TITLE
File logging

### PR DESCRIPTION
**Pull request by deldesir**
This feature adds a log file named "run.log" at /output with each run.

### CODE REVIEW

**Comment by deldesir** [comment]
The file created is used to store log information about each session that is run.

It also specify in the log which session just ran. This is useful for keeping track of which sessions have been run and for debugging purposes.

To implement this feature, I have enabled a file handler in youtube2zim/constant.py for zimscraperlib logger that writes to the run.log file. The logger formats the log at the beginning and end of each session to mark the start and end of the session in the log file.

I have also added some error handling to ensure that the log file is properly created and written to in case of any issues.

I tested it on Ubuntu 22.10 and 23.04.

**Comment by holta** [comment]
@georgejhunt can you review &/or merge this PR?

(Sequencing may need thinking over?  e.g. How best to prioritize other PR's like...)

- Custom Video Titles
- Metadata Summarization [ average video length HH: MM:SS, video count ]
- `--banner` thumbnailing fixes
- Other needs?

**Comment by holta** [comment]
@georgejhunt @prikeshsavla

Any objections to merging this PR?

Thanks for any suggestions you might have!!

**Comment by georgejhunt** [comment]
I don't know the plan. It looks like merging into main will create a chain
of changes which will diverge from kiwix's main. That might make it hard to
rebase in order to incorporate any fixes or changes kiwix makes.

I'd prefer any modifications to be made to another branch (maybe
"iiab-additions") which then can easily be rebased on top of kiwix main. I
don't think it is a reasonable expectation that kiwix will accept all of
our suggestions into their upstream. Or maybe you have another proposal.

**Comment by holta** [comment]
1) _Excellent Point_ that a rebasing / alignment strategy needs to be articulated (and enforced ;).  So this repo co-evolves in a very healthy way, right alongside https://github.com/openzim/youtube 👍

2) At the same time KISS naming simplicity (https://github.com/iiab/youtube i.e. branch `main`) can be incredibly valuable, bringing more community transparency.  If this already implies "IIAB Additions" — so long as git is used thoughtfully & conscientiously to rebase / realign regularly every few months _(the central question indeed!)_

3) Feeder forks like https://github.com/deldesir/youtube and their own branches might be the most valuable & explicitly clear, in most circumstances?  Whereas https://github.com/iiab/youtube branches (can sometimes!) feel like completely unnecessary bureaucracy.

   Conversely: if and when iiab/youtube branches sometimes spur collaboration ~ prototyping ~ testing of larger features, adding value bringing genuine focus, that could be incredibly valuable...

4) One such https://github.com/iiab/youtube branch could be explicitly named `upstream` — to carry (cache) the most recent upstream code that we're relying on.  As a safeguard more than anything else, to help with regular rebasing?

Anyway that's my initial proposal for consideration!

_Let's give this 24h-or-so to ponder ?_ 🤔

**Comment by georgejhunt** [comment]
I think you are proposing that kiwix/main be renamed iiab/upstream -- which
I oppose strongly. It makes no sense to me to clone kiwix, and then change
the name of the main branch, such that a git pull kiwix/main will fail.

Normally I just do "git pull main", "git checkout iiab", "git rebase
-Xtheirs main" in order to incorporate upstream modifications in my code. I
think this is simple and not at all confusing.



But I

**Comment by holta** [comment]
I sense that @georgejhunt is not understanding me.

I'll try to call him in coming days when he's hopefully available :crossed_fingers:

I'd like to understand his workflow better.

So this can align with end-user community documentation that is completely bureaucracy-free &mdash; actual users should be able to clone from https://github.com/iiab/youtube without even being aware of developers' raw materials (branches or otherwise).

**Pull request closed without merging**
