### PR TITLE
Fix error on unordered ids

### PR DESCRIPTION
**Pull request by deldesir**
This PR ensure the titles replacement loop doesn't break in case the video IDs are not in the same order as the titles.

### CODE REVIEW

**Comment by holta** [comment]
Great!  @deldesir is this tested?

@prikeshsavla can you quickly review if possible?

**Comment by deldesir** [comment]
Yes, smoke and functional tested.

**Comment by holta** [comment]
Is implementing `--custom-titles <youtube-video-ids.txt> <custom-video-titles.txt>` the high-level goal here?

- https://github.com/georgejhunt/youtube/pull/4#issuecomment-1305734918

Are some of the 4 exception-handling scenarios (described in the link above) being handled?

**Comment by deldesir** [comment]
I come to the conclusion ERROR #2 as per  https://github.com/georgejhunt/youtube/pull/4#issuecomment-1305734918 was not handled properly. I assumed all the videos IDs were present in the playlist in my last tests, but there were, in fact, one missing in the playlist I used

**Comment by holta** [comment]
> Is implementing `--custom-titles <youtube-video-ids.txt> <custom-video-titles.txt>` the high-level goal here?

The answer is YES (to help @prikeshsavla and @georgejhunt understand the purpose of this PR).

> * [Replace titles of all videos in a youtube playlist  georgejhunt/youtube#4 (comment)](https://github.com/georgejhunt/youtube/pull/4#issuecomment-1305734918)
> 
> Are some of the 4 exception-handling scenarios (described in the link above) being handled?

@deldesir clarified that:

- "ERROR 2" might not need to be handled in future, e.g. if a YouTube playlist is just no longer needed, as seems increasingly likely.

- "ERROR 4" is not yet being handled.  He/we should implement some kind of "fast" (upfront, fail fast!) error-handling in coming weeks, to inform the operator that ZIM files of this nature do not (currently) allow any duplicate/colliding video titles?

   _OR:_ We might choose to de-dupe the video titles (?) such that 5 videos that happen to have identical titles like "Matthew's Summer Vacation" ...are automatically de-duped (when constructing the ZIM file) ...to URL's roughly like the following?

   - http://box/.../matthews_summer_vacation
   - http://box/.../matthews_summer_vacation2
   - http://box/.../matthews_summer_vacation3
   - http://box/.../matthews_summer_vacation4
   - http://box/.../matthews_summer_vacation5

**Comment by holta** [comment]
Let's merge this PR within 24h ✅

(If @prikeshsavla or @georgejhunt have any Python or linting suggestions, Great!)

**Pull request merged**
